/* Teste de integração em navegador. Requer Playwright instalado fora da aplicação. */
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
    const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
    const page = await browser.newPage({ viewport: { width: 1365, height: 900 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('dialog', dialog => dialog.accept());
    const check = (condition, message) => { assert.ok(condition, message); console.log('OK:', message); };
    try {
        await page.goto(process.env.TEST_URL || 'http://127.0.0.1:8000', { waitUntil: 'networkidle' });
        check(await page.locator('.request-tile').count() === 2, 'Mural apresenta somente pedidos abertos ou em análise');
        check(await page.locator('.maker-card').count() === 2, 'Prestadores e reputação carregam');
        await page.locator('.category-link[data-category="Artesanato"]').click();
        check(await page.locator('.request-tile').count() === 0, 'Categorias e estado vazio funcionam');
        await page.getByRole('button', { name: 'limpar filtros', exact: true }).click();
        await page.locator('#makerCategory').selectOption('Artesanato');
        check(await page.locator('.maker-card').count() === 1, 'Filtro de especialidade seleciona prestador');
        await page.locator('#makerCategory').selectOption('');
        await page.locator('#makerPrice').selectOption('100');
        await page.locator('#makerRating').selectOption('4.5');
        check(await page.locator('.maker-card').count() === 2, 'Filtros de preço e reputação combinam');
        await page.locator('.maker-card button').first().click();
        check(await page.locator('#modalMaker').isVisible(), 'Perfil público abre com portfólio, estoque e avaliações');
        await page.keyboard.press('Escape');
        check(!await page.locator('#modalMaker').isVisible(), 'Escape fecha modal');
        for (const width of [320, 390, 768, 1024, 1365]) {
            await page.setViewportSize({ width, height: 900 });
            check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Sem overflow horizontal em ${width}px`);
        }
        await page.setViewportSize({ width: 390, height: 844 });
        await page.evaluate(() => App.openNewRequestModal());
        await page.locator('#reqTitle').fill('Vaso geométrico personalizado');
        await page.locator('#reqCategory').selectOption('Impressão 3D');
        await page.locator('#reqBudget').fill('100');
        await page.locator('#reqDeadline').fill('2035-12-20');
        await page.locator('#reqDescription').fill('Vaso em PLA terracota de 15 centímetros.');
        await page.locator('#reqFileInput').setInputFiles({ name: 'referencia.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jOioAAAAASUVORK5CYII=', 'base64') });
        await page.waitForFunction(() => App.activeAttachments.length === 1);
        await page.locator('#formRequest button[type="submit"]').click();
        check(await page.locator('#modalConfirmRequest').isVisible(), 'Publicação exige revisão do pedido no celular');
        await page.locator('#modalConfirmRequest button[onclick*="executePublishRequest"]').click();
        const reqId = await page.evaluate(() => StorageService.getRequests().find(r => r.title === 'Vaso geométrico personalizado').id);
        check(await page.evaluate(id => StorageService.getRequestById(id).attachments[0].url.startsWith('data:image/png'), reqId), 'Anexo local é persistido com conteúdo');
        await page.reload({ waitUntil: 'domcontentloaded' });
        check(await page.evaluate(id => !!StorageService.getRequestById(id), reqId), 'Pedido persiste após recarregar');
        await page.evaluate(id => { App.switchUser('usr_carlos'); App.openSendOfferModal(id); }, reqId);
        await page.locator('#offerPrice').fill('90');
        await page.locator('#offerDeadline').fill('2035-12-21');
        await page.locator('#offerNotes').fill('Impressão em PLA, acabamento fosco.');
        await page.locator('#modalOfferSend form').evaluate(form => form.requestSubmit());
        check(await page.evaluate(id => StorageService.getOffers(id).length === 0, reqId), 'Oferta com prazo incompatível é bloqueada');
        await page.locator('#offerDeadline').fill('2035-12-15');
        await page.locator('#modalOfferSend form').evaluate(form => form.requestSubmit());
        const offerId = await page.evaluate(id => StorageService.getOffers(id)[0].id, reqId);
        check(Boolean(offerId), 'Prestador envia oferta válida');
        await page.evaluate(id => App.acceptOffer(id), offerId);
        check(!await page.locator('#modalPayment').isVisible(), 'Prestador não aceita a própria oferta');
        await page.evaluate(id => { App.switchUser('usr_mariana'); App.acceptOffer(id); }, offerId);
        await page.locator('#formPayment').evaluate(form => form.requestSubmit());
        check(await page.evaluate(id => StorageService.getRequestById(id).productionStatus === 'Recebido', reqId), 'Aceite e pagamento simulado iniciam produção');
        await page.evaluate(() => App.navigateTo('in-progress'));
        await page.locator(`#chatInput_${reqId}`).fill('porra');
        await page.locator(`#chatInput_${reqId}`).press('Enter');
        check(await page.evaluate(id => StorageService.getMessages(id).length === 0, reqId), 'Moderação impede mensagem ofensiva');
        await page.locator(`#chatInput_${reqId}`).fill('Podemos manter a cor terracota?');
        await page.locator(`#chatInput_${reqId}`).press('Enter');
        check(await page.evaluate(id => StorageService.getMessages(id).length === 1, reqId), 'Chat envia mensagem válida');
        await page.evaluate(id => App.advanceProductionStatus(id), reqId);
        check(await page.evaluate(id => StorageService.getRequestById(id).productionStatus === 'Recebido', reqId), 'Cliente não altera produção');
        await page.evaluate(id => { App.switchUser('usr_carlos'); for (let i = 0; i < 5; i++) App.advanceProductionStatus(id); App.confirmReceipt(id); }, reqId);
        check(await page.evaluate(id => StorageService.getRequestById(id).productionStatus === 'Entregue' && StorageService.getRequestById(id).status === 'Em andamento', reqId), 'Entrega aguarda confirmação exclusiva do cliente');
        await page.evaluate(id => { App.switchUser('usr_mariana'); App.confirmReceipt(id); App.openReviewModal(id, 'usr_carlos', 'seller'); }, reqId);
        await page.locator('#reviewComment').fill('Ótimo acabamento e comunicação.');
        await page.locator('#modalReview form').evaluate(form => form.requestSubmit());
        check(await page.evaluate(id => StorageService.getReviews().filter(r => r.requestId === id).length === 1, reqId), 'Cliente avalia após recebimento');
        await page.evaluate(id => { App.openReviewModal(id, 'usr_carlos', 'seller'); App.handleSaveReview({ preventDefault() {} }); App.closeModal('modalReview'); }, reqId);
        check(await page.evaluate(id => StorageService.getReviews().filter(r => r.requestId === id).length === 1, reqId), 'Avaliação duplicada é bloqueada');
        await page.evaluate(() => { App.switchUser('usr_lucas'); App.openCancelRequestModal('req_103'); });
        await page.locator('#cancelReason').fill('O projeto não será mais necessário.');
        await page.locator('#formCancelRequest').evaluate(form => form.requestSubmit());
        check(await page.evaluate(() => StorageService.getRequestById('req_103').status === 'Cancelado'), 'Participante cancela durante produção com justificativa');
        await page.evaluate(() => { App.switchUser('usr_carlos'); App.openPortfolioModal(); });
        await page.locator('#portTitle').fill('Apresentação do ateliê');
        await page.locator('#portDescription').fill('Portfólio de trabalhos em impressão 3D.');
        await page.locator('#portImageUpload').setInputFiles({ name: 'portfolio.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n%%EOF') });
        await page.waitForFunction(() => document.getElementById('portImage').value.startsWith('data:application/pdf'));
        await page.locator('#formPortfolio').evaluate(form => form.requestSubmit());
        check(await page.evaluate(() => StorageService.getUserById('usr_carlos').sellerData.portfolio.some(item => item.image.startsWith('data:application/pdf'))), 'Portfólio PDF é salvo');
        for (const view of ['client-requests', 'seller-panel', 'in-progress', 'profile', 'explore']) {
            await page.evaluate(view => App.navigateTo(view), view);
            check(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `Tela ${view} cabe no celular`);
        }
        await page.evaluate(() => { App.logout(); App.closeModal('modalAuth'); App.navigateTo('profile'); });
        check(await page.locator('#modalAuth').isVisible(), 'Área privada exige autenticação');
        await page.evaluate(() => { App.closeModal('modalAuth'); App.switchUser('usr_mariana'); App.navigateTo('explore'); });
        await page.setViewportSize({ width: 1365, height: 900 });
        await page.screenshot({ path: '/tmp/tresde-desktop-final.png', fullPage: true });
        await page.setViewportSize({ width: 390, height: 844 });
        await page.screenshot({ path: '/tmp/tresde-mobile-final.png', fullPage: true });
        check(errors.length === 0, `Sem erros de JavaScript: ${errors.join('; ')}`);
    } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
